{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) (not .Values.auth.acl.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- if (include "redis.annotations" .) }}
  annotations:
{{- include "cloudpirates.tplvalues.render" (dict "value" (include "redis.annotations" .) "context" .) | indent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" (include "cloudpirates.namespace" .) (include "redis.fullname" .)) }}
  {{- $existingPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingPassword = index $existingSecret.data "redis-password" }}
  {{- end }}
  {{- $redisPassword := $existingPassword | default (.Values.auth.password | default (randAlphaNum 16) | b64enc) }}
  {{- $host := printf "%s.%s.svc" (include "redis.fullname" .) (include "cloudpirates.namespace" .) }}
  {{- $port := ternary (.Values.tls.port | toString) (.Values.service.port | toString) .Values.tls.enabled }}
  {{- $username := "default" }}
  {{- $scheme := ternary "rediss" "redis" .Values.tls.enabled }}
  redis-password: {{ $redisPassword | quote }}
  host: {{ $host | b64enc | quote }}
  port: {{ $port | b64enc | quote }}
  username: {{ $username | b64enc | quote }}
  uri: {{ printf "%s://%s:%s@%s:%s" $scheme $username ($redisPassword | b64dec) $host $port | b64enc | quote }}
{{- end }}